### ISSUE TITLE
Resolve lvm_t denials

### ISSUE THREAD

**Issue by mpalmi** [TresysTechnology/clip#128]
In order to get this system booting in Enforcing, we will need to resolve the remaining kernel_t denials.

Assumptions:
- Work will be done off of mpalmi/clip@95bafa004072cff0cfef3bf12e7357e0f1ad998b
- Allow rules are needed to get CLIP booting in Enforcing
- Least privilege access model will be employed
- refpolicy guidelines for policy [development](https://github.com/TresysTechnology/refpolicy/wiki/Documentation) will be followed.

Subtasks:
- [x] Figure out which process is creating /var/run/lvm/lvmetad.socket
- [x] Make sure /var/run/lvm/lvmetad.socket gets the proper label (lvm_var_run_t)

----

audit2allow
<pre>
#============= lvm_t ==============
allow lvm_t var_run_t:sock_file write;
</pre>

audit.log
<pre>
type=AVC msg=audit(1429891501.806:833): avc:  denied  { write } for  pid=1999 comm="pvscan" name="lvmetad.socket" dev="tmpfs" ino=9058 scontext=system_u:system_r:lvm_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=sock_file
</pre>

**Comment by mpalmi** [comment]
This is actually resolved as part of #118.
See:
https://github.com/mpalmi/clip/commit/7835ec6ddfffee0d6bac86df9190b3f5ddbed304#diff-5ed0b9578ae9eb749bd729aa3fb9343bR106

We might want to get rid of:
https://github.com/mpalmi/clip/commit/7835ec6ddfffee0d6bac86df9190b3f5ddbed304#diff-289c2ed7127da25039521676a20de8feR204

It seems unnecessary with the file context change.

**Comment by mpalmi** [comment]
@tomhurd Could you verify this please?

**Comment by mpalmi** [comment]
More denials on first boot:




>#============= lvm_t ==============
allow lvm_t hugetlbfs_t:dir getattr;

<pre>
type=AVC msg=audit(1432138294.256:59): avc:  denied  { getattr } for  pid=407 comm="lvm" path="/dev/hugepages" dev="hugetlbfs" ino=9494 scontext=system_u:system_r:lvm_t:s0 tcontext=system_u:object_r:hugetlbfs_t:s0 tclass=dir
type=AVC msg=audit(1432138310.316:59): avc:  denied  { getattr } for  pid=408 comm="lvm" path="/dev/hugepages" dev="hugetlbfs" ino=8943 scontext=system_u:system_r:lvm_t:s0 tcontext=system_u:object_r:hugetlbfs_t:s0 tclass=dir
</pre>

**Comment by tomhurd** [comment]
Thinks we should use fs_list_hugetlbfs(lvm_t) instead of fs_manage_hugetlbfs_dirs(lvm_t)

Denials from @ykhodorkovskiy with the two lvm commits removed:

type=AVC msg=audit(1432673317.743:55): avc:  denied  { getattr } for  pid=626 comm="lvm" path="/dev/hugepages" dev="hugetlbfs" ino=10202 scontext=system_u:system_r:lvm_t:s0 tcontext=system_u:object_r:hugetlbfs_t:s0 tclass=dir
type=AVC msg=audit(1432673317.750:56): avc:  denied  { read } for  pid=626 comm="lvm" name="/" dev="hugetlbfs" ino=10202 scontext=system_u:system_r:lvm_t:s0 tcontext=system_u:object_r:hugetlbfs_t:s0 tclass=dir
type=AVC msg=audit(1432673317.750:56): avc:  denied  { open } for  pid=626 comm="lvm" path="/dev/hugepages" dev="hugetlbfs" ino=10202 scontext=system_u:system_r:lvm_t:s0 tcontext=system_u:object_r:hugetlbfs_t:s0 tclass=dir
type=AVC msg=audit(1432673317.757:57): avc:  denied  { getattr } for  pid=626 comm="lvm" path="socket:[10577]" dev="sockfs" ino=10577 scontext=system_u:system_r:lvm_t:s0 tcontext=system_u:system_r:init_t:s0 tclass=unix_stream_socket
type=AVC msg=audit(1432673354.566:55): avc:  denied  { getattr } for  pid=624 comm="lvm" path="/dev/hugepages" dev="hugetlbfs" ino=10182 scontext=system_u:system_r:lvm_t:s0 tcontext=system_u:object_r:hugetlbfs_t:s0 tclass=dir
type=AVC msg=audit(1432673354.582:56): avc:  denied  { read } for  pid=624 comm="lvm" name="/" dev="hugetlbfs" ino=10182 scontext=system_u:system_r:lvm_t:s0 tcontext=system_u:object_r:hugetlbfs_t:s0 tclass=dir
type=AVC msg=audit(1432673354.582:56): avc:  denied  { open } for  pid=624 comm="lvm" path="/dev/hugepages" dev="hugetlbfs" ino=10182 scontext=system_u:system_r:lvm_t:s0 tcontext=system_u:object_r:hugetlbfs_t:s0 tclass=dir
type=AVC msg=audit(1432673354.602:57): avc:  denied  { getattr } for  pid=624 comm="lvm" path="socket:[10559]" dev="sockfs" ino=10559 scontext=system_u:system_r:lvm_t:s0 tcontext=system_u:system_r:init_t:s0 tclass=unix_stream_socket

**Comment by mpalmi** [comment]
No more lvm_t denials as of @425122f7595b33223fafbac1f48ed2bdcc68eb14

**Comment by mpalmi** [comment]
Need to address this with `fs_list_hugetlbfs(lvm_t)` before the Beta.

**Comment by mpalmi** [comment]
@ykhodorkovskiy

**Comment by mpalmi** [comment]
Reviewed and merged.
