### ISSUE TITLE
Document adding an upstream package to the packages/ directory

### ISSUE THREAD

**Issue by ykhodorkovskiy** [TresysTechnology/clip#83]

**Comment by minapoli** [comment]
Step 3 under Custom Packages states that 
"...you must update the PACKAGES variable in the top-level CONFIG_BUILD file to ensure the package is generated as part of any build"

There is no PACKAGES variable in CONFIG_BUILD.  If this isn't used anymore, then this line should be removed from the instructions. Otherwise, a placeholder variable should be added to CONFIG_BUILD.

**Comment by ykhodorkovskiy** [comment]
Fixed and also added clickable links which should be easier to follow.

**Comment by minapoli** [comment]
Spelling error in the modified section "Makeifle"
